apiVersion: v1
kind: Pod
metadata:
  name: capability-test
spec:
  containers:
    - name: demo
      image: ubuntu:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      command:
        - "sleep"
        - "1000"
      securityContext:
        capabilities:
          add:
            - "NET_ADMIN"
            - "CHOWN"
